"""Regenerate topics/*.md tables from *Tags: ...* lines in problems/**/*.md.

Each topic page has an autogenerated block delimited by:
  <!-- AUTOGEN-START -->
  ...
  <!-- AUTOGEN-END -->

Anything outside the block (heading, description, notes) is preserved.

Usage:
  python scripts/build_topic_indices.py
"""

from __future__ import annotations

import pathlib
import re
import sys
from collections import defaultdict

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
PROBLEMS_DIR = REPO_ROOT / "problems"
TOPICS_DIR = REPO_ROOT / "topics"

COMPETITION_DISPLAY = {"amc8": "AMC 8", "amc10": "AMC 10", "amc12": "AMC 12", "aime": "AIME"}

AUTOGEN_START = "<!-- AUTOGEN-START -->"
AUTOGEN_END = "<!-- AUTOGEN-END -->"


def parse_exam_file(path: pathlib.Path) -> list[tuple[int, list[str]]]:
    text = path.read_text(encoding="utf-8")
    problems: list[tuple[int, list[str]]] = []
    pattern = re.compile(r"^## Problem (\d+)\s*\n\s*\*Tags:\s*(.+?)\s*\*", re.MULTILINE)
    for m in pattern.finditer(text):
        n = int(m.group(1))
        tags = [t.strip().lower() for t in m.group(2).split(",") if t.strip()]
        problems.append((n, tags))
    return problems


def competition_year_variant(path: pathlib.Path) -> tuple[str, str, str]:
    competition = path.parent.name
    stem = path.stem
    m = re.match(r"^(\d{4})([A-Za-z]*)$", stem)
    if not m:
        return competition, stem, ""
    return competition, m.group(1), m.group(2)


def collect_entries() -> dict[str, list[tuple[str, str, str, int, list[str], pathlib.Path]]]:
    by_topic: dict[str, list[tuple[str, str, str, int, list[str], pathlib.Path]]] = defaultdict(list)
    for md in sorted(PROBLEMS_DIR.rglob("*.md")):
        if md.name == "README.md":
            continue
        competition, year, variant = competition_year_variant(md)
        for n, tags in parse_exam_file(md):
            for tag in tags:
                by_topic[tag].append((competition, year, variant, n, tags, md))
    return by_topic


def sort_key(entry: tuple[str, str, str, int, list[str], pathlib.Path]):
    competition, year, variant, n, _tags, _path = entry
    comp_order = ["amc8", "amc10", "amc12", "aime"]
    comp_idx = comp_order.index(competition) if competition in comp_order else len(comp_order)
    return (comp_idx, competition, year, variant, n)


def build_table(entries: list[tuple[str, str, str, int, list[str], pathlib.Path]], topic: str) -> str:
    lines = ["| Competition | Year | Problem | Subtopics |", "|-------------|------|---------|-----------|"]
    for competition, year, variant, n, tags, path in sorted(entries, key=sort_key):
        comp_display = COMPETITION_DISPLAY.get(competition, competition.upper())
        comp_col = f"{comp_display} {variant}".strip()
        rel_path = path.relative_to(TOPICS_DIR.parent).as_posix()
        link = f"[#{n}](../{rel_path}#problem-{n})"
        subtopics = ", ".join(t for t in tags if t != topic) or "—"
        lines.append(f"| {comp_col} | {year} | {link} | {subtopics} |")
    return "\n".join(lines)


def replace_autogen_block(text: str, new_block: str) -> str:
    if AUTOGEN_START in text and AUTOGEN_END in text:
        pattern = re.compile(re.escape(AUTOGEN_START) + r".*?" + re.escape(AUTOGEN_END), re.DOTALL)
        return pattern.sub(f"{AUTOGEN_START}\n\n{new_block}\n\n{AUTOGEN_END}", text)
    return text.rstrip() + f"\n\n{AUTOGEN_START}\n\n{new_block}\n\n{AUTOGEN_END}\n"


def rewrite_topic(path: pathlib.Path, block: str) -> None:
    existing = path.read_text(encoding="utf-8") if path.exists() else f"# {path.stem.replace('-', ' ').title()}\n\n"
    updated = replace_autogen_block(existing, block)
    path.write_text(updated, encoding="utf-8")


def rewrite_topics_readme(by_topic: dict) -> None:
    """Regenerate topics/README.md as a sorted index of every topic page."""
    lines = [
        "# Topics",
        "",
        "Each topic page lists every problem tagged with that technique / theorem / area across all competitions. Click any row to jump into the problem inside its exam file.",
        "",
        "## Index",
        "",
    ]
    for topic in sorted(by_topic.keys()):
        count = len(by_topic[topic])
        display = topic.replace("-", " ")
        lines.append(f"- [{display}]({topic}.md) — {count}")
    lines += [
        "",
        "## Tag conventions",
        "",
        "- Lowercase, hyphenated, apostrophes stripped (e.g. `vietas-formulas`, not `Vieta's Formulas`).",
        "- Prefer narrow techniques / formulas / theorems over broad areas. Broad tags (`algebra`, `geometry`, `number-theory`, `combinatorics`, `probability`, `sequences-and-series`, `trigonometry`) are fallbacks when no narrow tag matches.",
        "- Tags are assigned by `scripts/retag.py` scanning solution text. Edit the `*Tags:*` line inside each exam file under `problems/` and rerun `scripts/build_topic_indices.py` to refresh these tables.",
        "",
    ]
    (TOPICS_DIR / "README.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    by_topic = collect_entries()
    if not by_topic:
        print("no tagged problems found under problems/ — nothing to do.")
        return 0

    written = 0
    for topic, entries in by_topic.items():
        topic_path = TOPICS_DIR / f"{topic}.md"
        if not topic_path.exists():
            display = topic.replace("-", " ")
            topic_path.write_text(f"# {display}\n\nProblems tagged `{topic}`.\n", encoding="utf-8")
        table = build_table(entries, topic)
        rewrite_topic(topic_path, table)
        written += 1
    rewrite_topics_readme(by_topic)
    print(f"done. updated {written} topic file(s) and topics/README.md.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
